format_code_in_doc_comments = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
